services:
  db:
    build:
      context: ./mysql
    container_name: julias_mysql_container
    restart: always
    environment:
      DB_ROOT_PASSWORD: root
      DB_NAME: wordpress_db
      DB_USER: userdb
      DB_USER_PASSWORD: passworddb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    depends_on:
      - db
    build:
      context: ./wordpress
    container_name: julias_wordpress_container
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8080:80"

volumes:
  db_data:
  wordpress_data:
